### ISSUE TITLE
Bindings while running wrangler pages dev

### ISSUE THREAD

**Issue by gerhardcit** [elithrar/svelte-demo-d1#1]
This is all fine and well, but is there in wrangler 3 a method yet to bind platform.env.DB while running in dev mode?

**Comment by elithrar** [comment]
@gerhardcit 

```
npx wrangler pages dev --d1=DB -- npm run dev
```

**Comment by gerhardcit** [comment]
seems like you haven't tried it.

start you app as indicated:

`
npx wrangler pages dev --d1=DB -- npm run dev
`
 the test the api
 `curl http://127.0.0.1:8788/api/users`

you will get this
 
```
✘ [ERROR] [proxy]: TypeError: Cannot read properties of undefined (reading 'env')

      at GET (/svelte-demo-d1/src/routes/api/users/+server.ts:4:31)
```

this issue is mentioned here:
https://kit.svelte.dev/docs/adapter-cloudflare#bindings-testing-locally

in wrangler v2 there were hacks with miniflare.. but since wrangler v3, I'm yet to find a real solution to develop sveltekit with bindings.

**Comment by gerhardcit** [comment]
See #3 for a PR created as an option on how to handle local dev using wrangler-proxy
